WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e10b8dc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e10ba410>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e10baa70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/window
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e12ba4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e12b8c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/se/log
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f61e12b9d20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/78c98cd584c6f3748351260cc1be7720/se/log